{
 "title": "Home",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "inbound connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "peerobserver_conn_inbound_current",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU (5min avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 - (avg by (host) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "All dashboards", "type": "dashlist", "gridPos": { "h": 27, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "node block height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "peerobserver_validation_block_connected_latest_height",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - (node_memory_Cached_bytes{} + node_memory_Buffers_bytes{})) / node_memory_MemTotal_bytes{} * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Failed services",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{state=\"failed\"} > 0",
     "legendFormat": "{{host}}: {{name}}"
    }
   ]
  },
  {
   "title": "Bitcoin Core node restarts",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "resets(peerobserver_rpc_uptime[1h]) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}